TaskManager/Controllers/AssignTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business;
using Entity;
using TaskManager.Models;
using TaskManager.Utils;
using System.Globalization;

namespace TaskManager.Controllers
{
    public class AssignTaskController : BaseController
    {
        //
        // GET: /AssignTask/

        public ActionResult Index(int id)
        {
            var task = TaskBO.GetById(id);
            if (task == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            var assignTasks = TaskBO.AssignTaskGetByTaskId(id);

            if (assignTasks != null && assignTasks.Count > 0)
            {
                for (int i = 0; i < assignTasks.Count; i++)
                {
                    assignTasks[i].User = UserBO.GetById(assignTasks[i].UserId);
                }
            }

            ViewBag.Task = task;

            return View(assignTasks);
        }
        public ActionResult MyTask(AssignTasksSearchModel searchmodel)
        {
            var listAssignTasks = new List<AssignTask>();
            if (searchmodel == null)
            {
                searchmodel = new AssignTasksSearchModel();
            }
            DateTime sdate;
            DateTime edate;
            DateTime.TryParseExact(searchmodel.StartDate, Helper.FormatDate,
                               new CultureInfo("en-US"),
                               DateTimeStyles.None,
                               out sdate);
            DateTime.TryParseExact(searchmodel.EndDate, Helper.FormatDate,
                               new CultureInfo("en-US"),
                               DateTimeStyles.None,
                               out edate);
            var assigntasks = TaskBO.AssignTaskSearch(searchmodel.Requirement, CurrentUser.Id, sdate, edate);
            if (assigntasks != null)
            {
                foreach (var item in assigntasks)
                {
                    item.Task = TaskBO.GetById(item.TaskId);
                    
                }
                listAssignTasks=assigntasks;
            }
            searchmodel.AssignTask = listAssignTasks;
            return View(searchmodel);
        }
        [HttpGet]
        public ActionResult Create(int id)
        {
            var task = TaskBO.GetById(id);
            if (task == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var assignTask = new AssignTask
                {
                    TaskId = id
                };
            ViewBag.Task = task;
            ViewBag.Users = UserBO.GetByDepartmentId(CurrentUser.DepartmentLeader);
            return View(assignTask);
        }

        [HttpPost]
        public ActionResult Create(AssignTask assignTask)
        {
            var task = TaskBO.GetById(assignTask.TaskId);
            if (task == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            
                assignTask.CreateBy = CurrentUser.Id;
                assignTask.CreateDate = DateTime.Now;
                assignTask.ModifyBy = CurrentUser.Id;
                assignTask.ModifyDate = DateTime.Now;

                if (!string.IsNullOrEmpty(assignTask.StartAndEndDate) && assignTask.StartAndEndDate.Split('-').Length == 2)
                {
                    var strStart = assignTask.StartAndEndDate.Split('-')[0].Trim();
                    var strEnd = assignTask.StartAndEndDate.Split('-')[1].Trim();
                    DateTime sdate;
                    DateTime edate;
                    if (DateTime.TryParseExact(strStart, Helper.FormatDate,
                                       new CultureInfo("en-US"),
                                       DateTimeStyles.None,
                                       out sdate))
                    {
                        assignTask.StartDate = sdate;
                    }

                    if (DateTime.TryParseExact(strEnd, Helper.FormatDate,
                                       new CultureInfo("en-US"),
                                       DateTimeStyles.None,
                                       out edate))
                    {
                        assignTask.EndDate = edate;
                    }

                    TaskBO.AssignTaskInsert(assignTask);
                    AlertBO.Insert(assignTask.Requirement, (int)AlertType.AssignTask, 0, assignTask.UserId);
                }
                return RedirectToAction("Index" , new {id = assignTask.TaskId});
            

            ViewBag.Task = task;
            ViewBag.Users = UserBO.GetByDepartmentId(CurrentUser.DepartmentLeader);
            return View(assignTask);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var assignTask = TaskBO.AssignTaskGetById(id);
            //AssignTask model;
            if (assignTask != null)
            {

                assignTask.StartAndEndDate = assignTask.StartDate.ToString(Helper.FormatDate) + " - " + assignTask.EndDate.ToString(Helper.FormatDate);
            }
            else
            {
                return RedirectToAction("NotFound", "Home");
            }
            ViewBag.Task = TaskBO.GetById(assignTask.TaskId);
            ViewBag.Users = UserBO.GetByDepartmentId(CurrentUser.DepartmentLeader);
            return View("Create", assignTask);
        }

        [HttpPost]
        public ActionResult Edit(AssignTask assignTask)
        {
            var assignTaskSave = TaskBO.AssignTaskGetById(assignTask.Id);

            if (assignTaskSave == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            if (assignTaskSave.UserId > 0)
            {
                assignTaskSave.UserId = assignTask.UserId;
                assignTaskSave.Requirement = assignTask.Requirement;
                assignTaskSave.ModifyBy = CurrentUser.Id;
                assignTaskSave.ModifyDate = DateTime.Now;

                if (!string.IsNullOrEmpty(assignTask.StartAndEndDate) && assignTask.StartAndEndDate.Split('-').Length == 2)
                {
                    var strStart = assignTask.StartAndEndDate.Split('-')[0].Trim();
                    var strEnd = assignTask.StartAndEndDate.Split('-')[1].Trim();
                    DateTime sdate;
                    DateTime edate;
                    if (DateTime.TryParseExact(strStart, Helper.FormatDate,
                                       new CultureInfo("en-US"),
                                       DateTimeStyles.None,
                                       out sdate))
                    {
                        assignTask.StartDate = sdate;
                    }

                    if (DateTime.TryParseExact(strEnd, Helper.FormatDate,
                                       new CultureInfo("en-US"),
                                       DateTimeStyles.None,
                                       out edate))
                    {
                        assignTask.EndDate = edate;
                    }

                    TaskBO.AssignTaskUpdate(assignTask);
                }
                return RedirectToAction("Index", new { id = assignTaskSave.TaskId });
            }

            ViewBag.Task = TaskBO.GetById(assignTask.TaskId);
            ViewBag.Users = UserBO.GetByDepartmentId(CurrentUser.DepartmentLeader);
            return View("Create", assignTask);
        }

        public ActionResult Delete(int id)
        {
            var assignTask = TaskBO.AssignTaskGetById(id);

            if (assignTask == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            TaskBO.AssignTaskDelete(id);
            AlertBO.Delete(id, (int)AlertType.AssignTask);
            return RedirectToAction("Index", new {id = assignTask.TaskId});
        }

        [HttpGet]
        public ActionResult UpdateEmployee(int id)
        {
            var subtask = TaskBO.AssignTaskGetById(id);
            if (subtask == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            ViewBag.SubTask = subtask;
            ViewBag.Task = TaskBO.GetById(subtask.TaskId);
            ViewBag.Users = UserBO.GetByDepartmentId(CurrentUser.DepartmentLeader);
            if (subtask.UserId <= 0 && ViewBag.Users != null && ViewBag.Users.Count > 0)
            {
                subtask.UserId = ViewBag.Users[0].Id;
            }
            return View();
        }

        [HttpPost]
        public ActionResult UpdateEmployee(int subtaskId,int userId)
        {
            var subtask = TaskBO.AssignTaskGetById(subtaskId);
            if (subtask == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            subtask.UserId = userId;
            TaskBO.AssignTaskUpdate(subtask);
            return RedirectToAction("Index", new { id = subtaskId });   
        } 
    }
}

TaskManager/Controllers/ReportController.cs
using Business;
using Entity;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Web.Mvc;
using TaskManager.Models;
using TaskManager.Utils;

namespace TaskManager.Controllers
{
    public class ReportController : BaseController
    {
        //
        // GET: /Report/

        public ActionResult Index(string date)
        {
            var lstreport=new List<Report>();
            DateTime sdate;
            if (!DateTime.TryParseExact(date, Helper.FormatDate,
                               new CultureInfo("en-US"),
                               DateTimeStyles.None,
                               out sdate))
            {
                sdate = DateTime.Now;
            }
            var reports=TaskBO.ReportByUserReportAndReportDate(CurrentUser.Id,sdate.ToString("dd/MM/yyyy"));
            if (reports != null && reports.Count > 0)
            {
                foreach (var item in reports)
                {
                    item.AssignTask = TaskBO.AssignTaskGetById(item.AssignTaskId);
                }
            }
            ViewBag.Date = sdate;
            return View (reports ?? new List<Report>());
        }
        public ActionResult OverDues(string date)
        {
            DateTime sdate;
            if (!DateTime.TryParseExact(date, Helper.FormatDate,
                               new CultureInfo("en-US"),
                               DateTimeStyles.None,
                               out sdate))
            {
                sdate = DateTime.Now;
            }
            var users = TaskBO.ReportsOverDues(CurrentUser.DepartmentLeader, sdate.ToString("dd/MM/yyyy"));
            ViewBag.Date = sdate;
            return View(users ?? new List<User>());
        }

        [HttpGet]
        public ActionResult Create(int assignTaskId)
        {
            var assignTask = TaskBO.AssignTaskGetById(assignTaskId);
            if (assignTask == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var report = new Report
                {
                    AssignTaskId = assignTaskId
                };
            PrepareData();
            return View(report);
        }

        [HttpPost]
        public ActionResult Create(Report model)
        {
            if (Validate(model))
            {
                var assignTask = TaskBO.AssignTaskGetById(model.AssignTaskId);
                var report = new Report
                    {
                        ReportResult = model.ReportResult,
                        AssignTaskId = model.AssignTaskId,
                        CompletedPercent = model.CompletedPercent,
                        NextTask = model.NextTask,
                        CreateDate = DateTime.Now,
                        ReportDate = new DateTime(DateTime.Now.Year,DateTime.Now.Month,DateTime.Now.Day),
                        CreateBy = CurrentUser.Id,
                        ModifyBy = CurrentUser.Id,
                        ModifyDate = DateTime.Now,
                        TaskId = assignTask != null ?assignTask.TaskId : 0,
                        UserReport = CurrentUser.Id,
                        CommentDate = DateTime.Now,
                        ReportType=model.ReportType
                    };
                TaskBO.ReportInsert(report);
                AlertBO.Insert(report.ReportResult, (int)AlertType.Report, 0, assignTask.CreateBy);
                TaskBO.AssignTaskUpdateCompleted(model.AssignTaskId, model.CompletedPercent);
                return RedirectToAction("Index");
            }
            PrepareData();
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var report = TaskBO.ReportGetById(id);
            if (report == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            PrepareData();
            return View("Create",report);
        }

        [HttpPost]
        public ActionResult Edit(Report model)
        {
            var report = TaskBO.ReportGetById(model.Id);
            if (report == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            if (Validate(model))
            {
                report.ReportResult = model.ReportResult;
                report.CompletedPercent = model.CompletedPercent;
                report.NextTask = model.NextTask;
                report.ModifyBy = CurrentUser.Id;
                report.ModifyDate = DateTime.Now;
                report.ReportType = model.ReportType;


                TaskBO.ReportUpdate(report);
                TaskBO.AssignTaskUpdateCompleted(report.AssignTaskId, model.CompletedPercent);
                return RedirectToAction("Index");
            }
            PrepareData();
            return View("Create",model);
        }

        public ActionResult Delete(int id)
        {
            TaskBO.ReportDelete(id);
            AlertBO.Delete(id, (int)AlertType.Comment);
            AlertBO.Delete(id, (int)AlertType.Report);
            return RedirectToAction("Index");
        }

        private bool Validate(Report model)
        {
            var check = true;

            if (string.IsNullOrEmpty(model.ReportResult))
            {
                ModelState.AddModelError("", "Report result is empty.");
                check = false;
            }

            return check;
        }

        public ActionResult ListReport(ReportSearchModel searchModel)
        {
            if (searchModel == null)
            {
                searchModel = new ReportSearchModel();
            }
            DateTime sdate;
            DateTime edate;
            DateTime.TryParseExact(searchModel.StartDate, Helper.FormatDate,
                               new CultureInfo("en-US"),
                               DateTimeStyles.None,
                               out sdate);
            DateTime.TryParseExact(searchModel.EndDate, Helper.FormatDate,
                               new CultureInfo("en-US"),
                               DateTimeStyles.None,
                               out edate);

            var reports = TaskBO.ReportSearch(searchModel.UserId, sdate, edate);
            
            var user = new List<User>
                {
                    new User {UserName = "-- All --"}
                };
            user.AddRange(UserBO.GetByDepartmentId(CurrentUser.DepartmentLeader));
            ViewBag.Users = user;
            var temReport = new List<Report>();
            if (reports != null && reports.Count > 0)
            {
                for (int i = 0; i < reports.Count; i++)
                {
                    reports[i].AssignTask = TaskBO.AssignTaskGetById(reports[i].AssignTaskId);
                    reports[i].Task = TaskBO.GetById(reports[i].AssignTask.TaskId);
                    reports[i].User = UserBO.GetById(reports[i].UserReport);

                    
                    if (reports[i].User.DepartmentId == CurrentUser.DepartmentLeader)
                    {
                        temReport.Add(reports[i]);    
                    }
                    
                }    
            }

            searchModel.Reports = temReport;
            return View(searchModel);
        }

        [HttpGet]
        public ActionResult Comment(int id)
        {
            var report = TaskBO.ReportGetById(id);
            if (report == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            return View(report);
        }

        [HttpPost]
        public ActionResult Comment(Report model)
        {
            var report = TaskBO.ReportGetById(model.Id);
            if (report == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            if (!string.IsNullOrEmpty(model.Comment))
            {
                report.Comment = model.Comment;
                report.CommentBy = CurrentUser.Id;
                report.CommentDate = DateTime.Now;
                TaskBO.ReportUpdate(report);
                AlertBO.Insert(report.Comment, (int)AlertType.Comment, 0, report.UserReport);
                return RedirectToAction("ListReport");
            }else
            {
                ModelState.AddModelError("", "Comment is not empty");
            }
            return View(report);
        }

        private void PrepareData() {
            ViewBag.ReportTypes = new List<dynamic>{
                new {
                    Text = "Day",
                    Value = 1
                },
                new {
                    Text = "Month",
                    Value = 2
                },
            };
        }

    }
}

TaskManager/Views/AssignTask/Create.cshtml
@model Entity.AssignTask
@{
    ViewBag.Title = "Assign task";
}

@section breadcrumb
{
    <li>@Html.ActionLink("Task manager", "Index", "Task")</li>
    <li>@Html.ActionLink("Assign task", "Index", "AssignTask", new {id = ViewBag.Task.Id})</li>
}

<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Sub task - @ViewBag.Task.Name</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="box-body">
            <div class="form-group">
                @Html.HiddenFor(m => m.TaskId)
                @Html.HiddenFor(m => m.UserId)
                @*<div class="col-md-6">
                    
                    <label for="userId">Employee</label>
                    @Html.DropDownListFor(m => m.UserId,  new SelectList(ViewBag.Users, "Id", "FullName"),new { @class = "form-control" })
                </div>*@
                    @*@Html.LabelFor(m => m.StartAndEndDate)*@
                    <label for="requirement">Start Date And End Date</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        @Html.TextBoxFor(m => m.StartAndEndDate, new { @class = "form-control pull-right" })
                    </div><!-- /.input group -->
            </div>
            <div class="form-group">
                <label for="requirement">Requirement</label>
                @Html.TextAreaFor(m => m.Requirement, new { @class = "form-control", rows = "5" })
            </div>
            @*@Html.ValidationSummary(true)*@
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="@Url.Action("Index", new {id = ViewBag.Task.Id})" class="btn btn-primary">Cancel</a>
        </div>
    }
</div>
@section Script
{
    <script type="text/javascript">
        $(function () {
            //Datetime mask
            $('#StartAndEndDate').daterangepicker({ format: 'MM/DD/YYYY' });
        });
    </script>
}

TaskManager/Views/AssignTask/Index.cshtml
@model List<Entity.AssignTask>
@using TaskManager.Utils
@{
    ViewBag.Title = "List of sub Tasks";
}

@section breadcrumb
{
    <li>@Html.ActionLink("Task Manager", "Index", "Task")</li>
    <li>@Html.ActionLink("Assign Task", "Index", "AssignTask", new {id = ViewBag.Task.Id})</li>
}
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">List of Sub Tasks - @ViewBag.Task.Name</h3>
            </div>
                
            <!-- /.box-header -->
            <div class="box-body table-responsive">
                @if (Helper.CurrentUser.IsManager)
                {
                    <a href="@Url.Action("Create", new {id=ViewBag.Task.Id})" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add New</a>
                }
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>
                                Employee
                            </th>
                            <th>
                                Sub task Name
                            </th>
                            <th>
                                Start date
                            </th>
                            <th>
                                End date
                            </th>
                            <th>
                                % Completed
                            </th>
                            <th style="width: 200px">Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                @if (item.User == null)
                                { 
                                    <td>

                                    </td>
                                }
                                else
                                {
                                    <td>
                                        @item.User.FullName
                                    </td>
                                }
                                <td>
                                    @item.Requirement
                                </td>
                                <td>
                                    @item.StartDate.ToString(Helper.FormatDate)
                                </td>
                                <td>
                                    @item.EndDate.ToString(Helper.FormatDate)
                                </td>
                                <td>
                                    @item.CompletedPercent%
                                </td>
                                <td>
                                    <a class="btn btn-default btn-flat" href="@Url.Action("Edit", new { id = item.Id })"><i class="fa fa-edit"></i></a>
                                    <a class="btn btn-default btn-flat" href="@Url.Action("Delete", new { id = item.Id })"><i class="fa fa-remove"></i></a>
                                    @if (Helper.CurrentUser.DepartmentLeader == ViewBag.Task.Leader)
                                    {
                                        <a class="btn btn-default btn-flat" href="@Url.Action("UpdateEmployee", "AssignTask", new { id = item.Id })">Assign task</a>    
                                    }
                                </td>
                                
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        $(function () {
            $('#example2').dataTable({
                "bPaginate": true,
                "bLengthChange": false,
                "bFilter": false,
                "bSort": false,
                "bInfo": true,
                "bAutoWidth": false,
                "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Tất cả"]],
                "iDisplayLength": 25,
            });
        });
</script>    
}

TaskManager/Views/AssignTask/MyTask.cshtml
@using TaskManager.Utils
@model TaskManager.Models.AssignTasksSearchModel
@{
    ViewBag.Title = "My Task";
}

@section breadcrumb
{
    <li>@Html.ActionLink("My Task", "MyTask", "AssignTask")</li>
}
<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Search</h3>
    </div>
    @using (Html.BeginForm())
    {
        <div class="box-body"> 
            <div class="form-group">
                <div class="col-md-4">
                    @Html.LabelFor(m => m.Requirement)
                    @Html.TextBoxFor(m => m.Requirement, new { @class = "form-control" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(m => m.StartDate)
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        @Html.TextBoxFor(m => m.StartDate, new { @class = "form-control"})
                    </div>
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(m => m.EndDate)
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        @Html.TextBoxFor(m => m.EndDate, new { @class = "form-control" })
                    </div>
                </div>
                @*<div class="col-md-4">
                    @Html.LabelFor(m => m.Leader)
                    @Html.DropDownListFor(m => m.Leader, new SelectList(ViewBag.Departments, "Id", "Name"), new { @class = "form-control" })
                </div>*@

            </div>
            <div class="clear"></div>
        </div>
        <div class="box-footer">
            <button type="submit" class="btn btn-primary pull-right">Search</button>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    }
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">List of Assign Tasks</h3>
            </div>
                
            <!-- /.box-header -->
            <div class="box-body table-responsive">
                
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>
                                Task Name
                            </th>
                            <th>
                                Priority
                            </th>
                            <th>
                                Requirement
                            </th>
                            <th>
                                Start Date
                            </th>
                            <th>
                                End Date
                            </th>
                            @*<th>
                                Leader of task
                            </th>*@
                            <th style="width: 200px">Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.AssignTask)
                        {
                            <tr>
                                <td>
                                    @item.Task.Name
                                </td>
                                <td>
                                    @item.Task.Priority.GetDescription()
                                </td>
                                <td>
                                    @item.Requirement
                                </td>
                                <td>
                                    @item.Task.StartDate.ToString(Helper.FormatDate)
                                </td>
                                <td>
                                    @item.Task.EndDate.ToString(Helper.FormatDate)
                                </td>
                                <td>
                                    <a class="btn btn-default btn-flat" href="@Url.Action("Create", "Report", new {assignTaskId=item.Id})">Report</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        $(function () {
            $('#example2').dataTable({
                "bPaginate": true,
                "bLengthChange": false,
                "bFilter": false,
                "bSort": false,
                "bInfo": true,
                "bAutoWidth": false,
                "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Tất cả"]],
                "iDisplayLength": 25,
            });
            $('#StartDate').datepicker();
            $('#EndDate').datepicker();
        });

        $("#StartDate, #EndDate").datepicker({
        });
        
</script>    
}

TaskManager/Views/AssignTask/ReportTask.cshtml
@{
    ViewBag.Title = "ReportTask";
}

<h2>ReportTask</h2>

TaskManager/Views/AssignTask/UpdateEmployee.cshtml
@{
    ViewBag.Title = "Assign task";
    var subTaskId = ViewBag.SubTask.Id.ToString();
}
@section breadcrumb
{
    
}
<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Assign task</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="box-body">
            <div class="form-group">
                    <label for="userId">Employee</label>
                    @Html.Hidden("subtaskId", (string)subTaskId)
                    @Html.DropDownList("userId",  new SelectList(ViewBag.Users, "Id", "FullName", ViewBag.SubTask.UserId),new { @class = "form-control" })
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="@Url.Action("Index", new {id = ViewBag.Task.Id})" class="btn btn-primary">Cancel</a>
        </div>
    }
</div>